### ISSUE TITLE
Error on editing categories

### ISSUE THREAD

**Issue by Nicola1971** [sazanof/MODxPlaning#1]
Trying to edit categories:

Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=2' at line 1

SQL > SELECT id,title,description FROM `modx_db`.`modx_planing_categories` WHERE =2

Basic info  
REQUEST_URI http://www.####.com/manager/index.php?a=112&id=10&cal_id=1&op=cat&cat_opt=edit&cid=2
Manager action  112 - Execute module
Referer http://www.####.com/manager/index.php?a=112&amp;id=10&amp;cal_id=1&amp;op=cat

Backtrace
include_once(string $var1)
manager/index.php on line 583
evalModule(string $var1, array $var2)
manager/processors/execute_module.processor.php on line 60
eval()
manager/processors/execute_module.processor.php on line 73
include_once(string $var1)
manager/processors/execute_module.processor.php(73) : eval()'d code on line 1
MODxPlaning->getCategory(2)
assets/modules/modxplaning/module.php on line 162
DBAPI->select('id,title,description', string $var2, '=2')
assets/modules/modxplaning/classes/modxplaning.class.php on line 61
DBAPI->query(string $var1)
manager/includes/extenders/dbapi.mysqli.class.inc.php on line 146

**Comment by sazanof** [comment]
Try now
[commit](https://github.com/sazanof/MODxPlaning/commit/a24a1086dfa624827a629c3c260638837631c2c8)

**Comment by Nicola1971** [comment]
Thank works.
Great Module
