### ISSUE TITLE
modal vs full

### ISSUE THREAD

**Issue by Nicola1971** [sazanof/MODxPlaning#2]
Can't understand difference between "modal" an "full" mode, both settings give me the same result (open the modal window)

`[!MODxPlaning? &calID=`1` &isClick=`1` &dayClick=`1` &jQ=`n` &mode=`modal`!]`

`[!MODxPlaning? &calID=`1` &isClick=`1` &dayClick=`1` &jQ=`n` &mode=`full`!]`

**Comment by sazanof** [comment]
You're right!
This "modal" option was in the previous version of this module - sorry! )
